### ISSUE TITLE
[Request for information] Is the extension working with a custom code-server ?

### ISSUE THREAD

**Issue by drupol** [coder/vscode-coder#100]
Hello,

I've installed a custom [code-server](https://github.com/coder/code-server) on my local network and I'm wondering if this extension can work with a custom local code server.

I can use the code-server with my browser, but when I try to connect to it with the extension, it tries to reach the page `http://<url-of-my-code-server>/cli-auth` and it returns a 404.

Thanks for helping me in advance.

**Comment by netlooker** [comment]
I can confirm that I stumbled on the same issue however on my side I get "Not found." response. I guess the "coder-remote" vs-code' plugin is not foreseen to interconnect without authentication.

**Comment by drupol** [comment]
I tried with and without auth, same result.

Is it because I'm using it in HTTP instead of HTTPS ?

**Comment by drupol** [comment]
Fair enough, thanks!

Maybe it would be nice to add it in the documentation.
