### ISSUE TITLE
Allow configuring the source and destination of the Coder binary

### ISSUE THREAD

**Issue by bashscr** [coder/vscode-coder#103]
Hey, thank you for taking your time to read this. 

Due to security policies in place, we are having issues using this extension without getting exceptions passed. It appears the `fetchBinary()` method in `storage.ts` is calling `getBinaryCachePath()` which uses `path.join(this.globalStorageUri.fsPath, "bin")` that returns `%APPDATA%\Code\User\globalStorage\coder.coder-remote\bin\`. Is it possible to either be able to choose where this bin gets stored/checked, or possibly update the `checkBinaryExists()` to check for system/user environment variables to see if the Coder CLI is already in the PATH? This would alleviate a lot of headaches if we could either choose the path to store the bin folder/file or be able to check to see if we already have a folder specified in our environment variables for the Coder CLI. No issues if the extension needs to update the Coder CLI in the environment variable PATH.

Please let me know if you have any thoughts/potential workarounds, thank you very much!

**Comment by code-asher** [comment]
I was just about to create this issue but saw it already exists!  

In the JetBrains plugin we added a setting that lets you configure the path of the binary so we should do the same here.

One use case seems to be configuring that to be some restricted location like in `Program Files` so when the binary is out of date and the plugin is out of date but cannot write to the provided directory we added two options:

- Disable the version check, always use the provided binary
- Fall back to the default, writable location
