### ISSUE TITLE
Forward SSH user agent

### ISSUE THREAD

**Issue by jonasbg** [coder/vscode-coder#109]
From the source code I am not able to find out if `ForwardAgent` setting is possible,
```
export interface SSHValues {
  Host: string
  ProxyCommand: string
  ConnectTimeout: string
  StrictHostKeyChecking: string
  UserKnownHostsFile: string
  LogLevel: string
  SetEnv?: string
}
```

I would like to use Yubikey to sign my git commits and use it for accessing git repos.

This works if I add `ForwardAgent=yes` to the `~/.ssh/config` file for Coder and use the remote SSH extension in VSCode.

**Comment by matifali** [comment]
![image](https://github.com/user-attachments/assets/5d5e1642-f155-4672-a42a-f1c5c6ab80e5)
If you go to Settings->Coder
It is now possible to set custom ssh config parameters.
