### ISSUE TITLE
Support for vscode.dev

### ISSUE THREAD

**Issue by Mrc527** [coder/vscode-coder#120]
Hello everyone,

I noticed I cannot install this lovely plugin in my vscode.dev environment.
I fully understand the reason but I would love to have it there. And It does not look like there is any issue about this.

So, any chance to have it compatible with the browser version of vscode.dev?

BTW, I know you can open the workspace directly in a browser but there you get stuck with other issues like not being able to sync your profile.

**Comment by kylecarbs** [comment]
There'd need to be movement from Microsoft on exposing the Remote API's to allow for easier remote connections. Right now, we depend on VS Code's Remote SSH extension, which will not work in the web.

**Comment by Mrc527** [comment]
But the "tunnel" support is there, any chance to make use of that instead?

**Comment by matifali** [comment]
@code-asher and I brainstormed on this one, and it looks possible. However, it will provide a similar experience to the [vscode-web](https://registry.coder.com/modules/vscode-web) module.

We can reopen if we see more demand.
