### ISSUE TITLE
Github Copilot installed on remote won't fetch completions unless "github.gitAuthentication" is enabled

### ISSUE THREAD

**Issue by BatCountry** [coder/vscode-coder#125]
I'm not certain that this doesn't break the copilot-mediated Github auth, but while trying to get Github Copilot working in my coder environment I discovered it was unable to make API calls and get a response until I edited the workspace settings JSON and removed the line: `"github.gitAuthentication": false`

Copilot immediately started working and offering suggestions.
I was using the built in `Develop in Kubernetes` template on Coder v2.0.2+76ad116

I'll try it on v2.1.0 when I get home from work, and close this issue if it doesn't work, but leaving this here for fellow travelers, and in case anything can be done on Coder's end.

**Comment by kylecarbs** [comment]
I don't have this behavior.

Are you on the latest version of Copilot and VS Code?

**Comment by BatCountry** [comment]
Yes to Copilot v1.104.341, VS Code 1.81.1, though I was using Coder Remote v0.1.20, which I see was updated since this morning, if that makes a difference.

I can confirm that after upgrading both Coder and Coder Remote I'm not experiencing the issue with Copilot anymore (and at some point the settings.json cleared themselves.) 

I'm prepared to call this operator error, but hopefully the noise about the `"github.gitAuthentication": false` setting will be useful for somebody.  Thanks.
