### ISSUE TITLE
Add Coder workspaces to remote explorer

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#14]
<img width="426" alt="Screen Shot 2023-01-06 at 12 19 28 PM" src="https://user-images.githubusercontent.com/22407953/211074014-a9e48a66-0204-474c-a0b3-c44fbe60056a.png">

**Comment by phorcys420** [comment]
This was closed as completed even though the feature isn't there, maybe it was removed?

![image](https://github.com/coder/vscode-coder/assets/57866459/3dfde191-c04b-4e08-91e8-5a8c5c87ea03)

**Comment by kylecarbs** [comment]
Click your Coder tab! AFAIK we'd have to use a private API to show up in that sidebar, which we could 🤫

**Comment by code-asher** [comment]
Ah yeah if we never had this IMO we close.

**Comment by phorcys420** [comment]
> Click your Coder tab! AFAIK we'd have to use a private API to show up in that sidebar, which we could 🤫

yeah I know about the tab but I discussed this idea with Ben because I think it would be nice for feature parity with other remote extensions and he told me to open an issue 😉

cc: @kylecarbs
