### ISSUE TITLE
Unable to connect on v0.1.27

### ISSUE THREAD

**Issue by maanex** [coder/vscode-coder#167]
Hello. I had to manually downgrade to v0.1.26 in order to connect to my coder instance. Here's the error I'm getting on 0.1.27

![image](https://github.com/coder/vscode-coder/assets/23345879/a92a6c53-6f4a-49f2-9930-057b603eba63)

**Comment by kylecarbs** [comment]
Odd. Are you using a development version of Coder? Or is this prod?

**Comment by kylecarbs** [comment]
Can you send me the output of `/api/v2/buildinfo`?

**Comment by maanex** [comment]
```json
{
  "external_url": "https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90",
  "version": "v2.3.3+e491217",
  "dashboard_url": "https://my.url.here",
  "workspace_proxy": false
}
```

**Comment by kylecarbs** [comment]
Odd. Investigating

**Comment by maanex** [comment]
Please note that this error only occurs when connecting through VSCode. I can still SSH onto the environment with no issues

**Comment by kylecarbs** [comment]
Ahh, fixing. I see the error, thanks for reporting.

**Comment by kylecarbs** [comment]
See https://github.com/coder/vscode-coder/pull/168

**Comment by kylecarbs** [comment]
Thanks for the quick report and reply @maanex!

**Comment by kylecarbs** [comment]
New release is out. Sorry about this!

Thanks @maanex :partying_face:

**Comment by maanex** [comment]
🥳
