### ISSUE TITLE
workspace bandwidth is not accurate

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#18]
<img width="754" alt="Screen Shot 2023-01-10 at 3 23 27 PM" src="https://user-images.githubusercontent.com/22407953/211665375-d485e6fa-3dc3-4fe6-8d35-aaeb0ebe9cd1.png">

I uploaded a 100MB file from https://speed.hetzner.de/ and the bandwidth didn't really change

**Comment by kylecarbs** [comment]
I believe this is primarily because of a P2P connection. @coadler any ideas? This uses the netinfo stuff you added.

**Comment by matifali** [comment]
@kylecarbs @coadler if we still want to solve it, please reopen. We did not have any other customer/user mention this bug yet.
