### ISSUE TITLE
URL should not be  required on login when it is predefined  on global storage

### ISSUE THREAD

**Issue by liorb-canva** [coder/vscode-coder#182]
**Context:**
For self hosteed coder server, a private url needed to be provided in login screen
This url is not alweys intuative and easy to remember

**Accepted behaviour**
If the URL is defined in global config or in the `CODER_URL` environment variable, do not show the user a prompt to fill the url, and redirect to the pre-defined url to login.

**Current Behaviour**
The login function, ignored the url stored in `Storage` class
![Screenshot 2023-12-18 at 10 15 38 am](https://github.com/coder/vscode-coder/assets/125318364/b04176a1-3488-4d98-b29d-b691322bda86)

**Comment by matifali** [comment]
While doing this, make sure it can also handle multiple coder deployments gracefully.

**Comment by code-asher** [comment]
I think we might still want to show the login prompt but just prefill it, otherwise what if you want to connect to a different deployment but it keeps auto-logging you into a different one?

**Comment by matifali** [comment]
The best would be to add the ability to list recently used URLs and prefilled the last connected one.
