### ISSUE TITLE
Clicking "Start Workspace" on stopped workspace prompt updates workspace to active template version

### ISSUE THREAD

**Issue by eswolinsky3241** [coder/vscode-coder#183]
When a Coder workspace is stopped, either manually or on a schedule, Any remote VSCode sessions connected to that workspace will display the below prompt to the user:

![image](https://github.com/coder/vscode-coder/assets/58117461/92ce8cf6-c36a-4664-9b23-68810db2ec14)

If the user clicks on "Start Workspace", Coder will start the workspace, as expected. However, what's not expected or desired is that it also updates the workspace to the active template version, without the permission of the user.

Before clicking "Start Workspace":
![image](https://github.com/coder/vscode-coder/assets/58117461/931b2353-34ac-4de0-8943-8feb2db77a7c)

After clicking "Start Workspace":
![image](https://github.com/coder/vscode-coder/assets/58117461/a44b2e86-f965-4795-9ef0-ef42e94eecb7)

Even if I click "Cancel" on the prompt or close the modal, it will still update my workspace to the active template version.

## Desired behavior
Clicking "Start Workspace" should only start the workspace, it should not update it to the active template version.

**Comment by liorb-canva** [comment]
+1  👍  from me on this as well. 
This is a much-needed improvement! 
On the Jetbrains plugin, this is already handled by showing the state of each workspace, so we will definately  want this behaviour in vscode as well 😄
