### ISSUE TITLE
Windows Firewall prompt on every new binary

### ISSUE THREAD

**Issue by deansheather** [coder/vscode-coder#23]
Every time there's a new version on the server (which is multiple times per day in dev.coder.com) the extension will download a new binary and Windows firewall will prompt to allow network access.

We should figure out a way to prevent the windows firewall thing from popping up (we only need to access over localhost anyways).

**Comment by kylecarbs** [comment]
@deansheather are you aware of a way for us to automagically do this? Maybe we'll have to sign the Windows binary........ :ghost:

**Comment by deansheather** [comment]
@kylecarbs Signing the binary doesn't help. As soon as you do any listening with a new binary you get a firewall popup unless the firewall is disabled completely.

![image](https://user-images.githubusercontent.com/11241812/212119854-378f2e24-2bc7-426b-9bae-f7ec7c59d532.png)

I think the only way to avoid this would be to listen on a named pipe instead of a TCP socket on Windows, which wouldn't trigger the firewall:

https://pkg.go.dev/github.com/Microsoft/go-winio?GOOS=windows#ListenPipe

**Comment by deansheather** [comment]
Turns out this is caused by tailscale and not listening because we listen over stdio anyways!

From my tests putting the binary in the same path causes the popup to only occur on the first time, even if the binary is changed.

**Comment by jsjoeio** [comment]
## Notes from chatting with Dean

Nicer solution. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Client can specify this. We can use a SHA256 of the binary and the server can see if it's set and it matches, it will not reply with binary and will reply 304 not-modified

"I already have this version. Here is the version (in the etag)"

Dean to make change on server
Joe to make change on frontend/inside the extension

**Comment by jsjoeio** [comment]
## Testing Locally

You can test the new server changes like so: 
WIP
