### ISSUE TITLE
How do I instal the code-server GitHub Copilot Extension?

### ISSUE THREAD

**Issue by rajaps369** [coder/vscode-coder#24]
I followed the instructions below and installed the github copilot extension on coder (code-server), but it is not enabled. 
How do I turn on Gothub Copilot on Code-Server?

https://coder.com/docs/code-server/latest/FAQ#how-do-I-Install-An-Extension

code-server --install-extension extension-id
code-server --install-extension github.copilot

**Comment by kylecarbs** [comment]
GitHub Copilot doesn't work with code-server, unfortunately. It does work with VS Code Remote though.
