### ISSUE TITLE
Detect extensions installed in code-server and offer to install them

### ISSUE THREAD

**Issue by ntimo** [coder/vscode-coder#25]
# Problem
Currently when using the vscode remote connect tool, VSCode does not share the extensions with code-server, this means users have to keep both tools in sync, which produces overhead.

# Desired solution 
The extensions installed on code-server in the workspace should be detected and automatically be installed when using VSCode Remotely with the extension.

**Comment by kylecarbs** [comment]
This can actually be fixed with documentation!

```
code-server --extensions-dir ~/.vscode-server/extensions
```

**Comment by jsjoeio** [comment]
@ntimo would love your input on https://github.com/coder/vscode-coder/pull/32

**Comment by ntimo** [comment]
> @ntimo would love your input on #32

I know I am a bit late to the party, but I love the docs 👍

**Comment by jsjoeio** [comment]
Better late than never! Glad to hear it 😄
