### ISSUE TITLE
Carry over code-server settings when connecting

### ISSUE THREAD

**Issue by ntimo** [coder/vscode-coder#26]
# Problem
Currently when using the vscode remote connect tool, VSCode does not share the settings with code-server, this means users have to keep both tools in sync, which produces overhead.

# Desired solution 
The settings users configured on code-server should be applied automatically when using the extension in the local vscode for the workspace.

**Comment by kylecarbs** [comment]
Users can do this in code-server by changing the configuration directory I believe... this is the preferred way to handle it. Otherwise, we end up making too many assumptions.

Let me know if I'm overlooking something please!
