### ISSUE TITLE
Investigate 302 connecting to workspace that is stopped

### ISSUE THREAD

**Issue by code-asher** [coder/vscode-coder#262]
![image_720](https://github.com/coder/vscode-coder/assets/45609798/c19ceb84-164e-4035-9cc5-8a939099598a)

The plugin starts a workspace (if needed) and waits until the workspace is ready before connecting, which makes me wonder:

- [x] Is it not following redirects?
- [x] If not, should it?
- [x] Or is there just a bug in this start and wait logic?
- [x] Why does this error not display the request details?  I thought we added that.

**Comment by Kira-Pilot** [comment]
https://codercom.slack.com/archives/C0530DKPE58/p1715297648070599
