### ISSUE TITLE
Remove old log files

### ISSUE THREAD

**Issue by code-asher** [coder/vscode-coder#270]
Currently you can infinitely accumulate logs (the ones produced by `--log-dir`).

Well, maybe not infinitely, if you restart your machine I guess it would reset the pid counter and overwrite old files, but still.

Probably easy enough to just delete everything older than n days?  Maybe we only do this if there are > n log files.

**Comment by code-asher** [comment]
It occurred to me that maybe the cleanup logic should be in the cli since it is the one generating the files?

**Comment by bcpeinhardt** [comment]
Closed with #322
