### ISSUE TITLE
Can't login when using self signed cert for coder server

### ISSUE THREAD

**Issue by ntimo** [coder/vscode-coder#29]
# Description
When trying to login on Windows to a coder server that is using a self signed cert by a private CA the login does not work and errors with:
![image](https://user-images.githubusercontent.com/6145026/212261297-0e5fcf71-f083-4ab4-89bd-24fd15ae4caa.png)

# Desired solution
It should be possible to tell the extension to accept the cert from the private CA.

**Comment by ChriZ982** [comment]
Hi @kylecarbs ,
is there any way to fix this in a short period of time? I would be happy to help 😃

**Comment by kylecarbs** [comment]
I'm not actually sure why this isn't working... it's odd that a status code 400 is used. Can you try manually requesting the URL from your computer? Does it work with our CLI?

**Comment by ChriZ982** [comment]
I think your merge request #36 changed the error message to the following:
`Invalid session token! (Error: unable to verify the first certificate)`

Do you get the same now @ntimo ?

`coder login` and `coder ssh` work just fine. The CA certificate is also stored in the Windows certificate store and accepted. Not sure why VS Code or this extension does not accept the certificate.

> Can you try manually requesting the URL from your computer?

@kylecarbs which URL do you mean exactly? The coder base URL is accepted just fine

**Comment by kylecarbs** [comment]
Ahh, I see. I wonder if it's due to our use of `axios`...

**Comment by kylecarbs** [comment]
@ChriZ982 I'm not able to find any good info on how to work around this... it seems like the certificate isn't being loaded by VS Code for some reason.

Can you try running VS Code with the `--ignore-certificate-errors` flag to see if that fixes it? I know that's not an actual fix, but it should help us narrow down whether it's us or not.

See: https://code.visualstudio.com/docs/setup/network#_ssl-certificates

**Comment by groucho64738** [comment]
I can confirm that setting that environment variable (on Windows), that I stop getting the error. It'd be nice if there were an environment variable that could be used to point to a certificate bundle instead. I tried NODE_EXTRA_CA_CERTS, but that didn't work for me.

**Comment by bashscr** [comment]
Hey @kylecarbs sorry to ping you on this issue. We are also facing the same problem here, getting an error about unable to verify the first certificate (error code 401 I believe). The only way I've been able to connect using VS Code Desktop is to set the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to 0. We are using self-signed certs generated from Venafi, which are applied & stored on our EC2 instance for Coder. Using the Coder CLI via my local machine is fine, as well as the VS Code in the browser option. However, this is a pretty big stopgap for us until we're able to use our local VS Code to connect to the Workspaces. Given the hacky workaround, which is also not recommended for Production, is there anything that can be remediated on this VS Code Extension to alleviate this potentially? Any feedback would be greatly appreciated, thank you!

![image](https://user-images.githubusercontent.com/51954831/234380364-2cfab0ef-edc7-4b16-90da-2b7b462685a9.png)
