### ISSUE TITLE
Updating of SSH config

### ISSUE THREAD

**Issue by mafredri** [coder/vscode-coder#30]
I noticed the extension adds it's own `Host coder-vscode--*` entry to SSH config, or more specifically. The file defined by:

```
	"remote.SSH.configFile": "/Users/maf/.ssh/coder"
```

I'm wondering it we should do one of two things:

1. Make sure we use a managed block, like we do with coder (`# ------------{START,END}-CODER------------`)
2. See if we can override `remote.SSH.configFile` when connecting

If it works, 2) would allow us to fully manage the file and not make changes in the users files, a very clean approach.

Alternatively 1) would be an improvement from current since we won't know if/when we'll need to make changes to the host configuration, and doing so automatically without a block is dangerous.

**Comment by kylecarbs** [comment]
The problem with 2) is that it's similar to how editing the SSH config file is, but globally for all of VS Code. It'd be nice if VS Code allowed settings to modify settings temporarily, but that'd be a bit weird.

**Comment by kylecarbs** [comment]
We now do this!
