### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by rhysjtevans** [coder/vscode-coder#300]
I have a proxy between the coder server and the desktops in an enterprise environment. 

When I use VSCode's Remote SSH it works when I use coder it doesn't. SSH works from the command line.

This points me to coder extension not respecting the proxy settings.

Anyone have any tips to troubleshoot further?

**Comment by code-asher** [comment]
Our extension delegates to the Remote SSH extension for the actual connection part, so my guess is that the failure is in one of the API calls me make before making the connection. 

Could you post the error you get to confirm?

If that is the case, I think we probably need to explicitly read the `http_proxy` environment variable and its friends, and `http.proxy` from VS Code settings as well.

**Comment by rhysjtevans** [comment]
Thanks for the quick response @code-asher.
I couldn't really see an error which is part of the problem.
1. Not sure where to look if I'm honest so some help here would be greatly appreciated. I'll see what I can find next week now I'm afraid.
2. The error I do see is simply a 503 from the default gateway which won't work

From what I have seen and experienced if it doesn't currently do that then that makes complete sense and for it to respect the vscode settings would be ideal 👍

**Comment by code-asher** [comment]
An error like 503 is what I was looking for, thank you!  Should be easy enough to fix this, I think.

**Comment by rhysjtevans** [comment]
if you want a tester, let me know

**Comment by code-asher** [comment]
Thank you!  Would you be able to download and test https://github.com/coder/vscode-coder/releases/tag/v1.1.0?

**Comment by rhysjtevans** [comment]
The change looks very promising - appreciate the quick turnaround @code-asher - I'll test it this Thursday

**Comment by code-asher** [comment]
Sounds good to me, no rush!  :grin:

**Comment by code-asher** [comment]
So, just FYI, I neglected to test the existing version of the plugin and I might not have actually fixed anything.  1.1.0 now explicitly reads and sets the proxy settings, but when I tested the 1.0.2 just now it actually already used the proxy?  Not sure how, unless VS Code is doing some monkey patch magic with the agent.  I tested both the `http.proxy` setting and the `http_proxy` environment variable, and both made the plugin use the proxy.

Which makes me think the issue might be something else.

**Comment by rhysjtevans** [comment]
Sorry for the delay @code-asher , I've tried the build and it definitely helped. I've got an SSH-based problem now. Once I've got that working I'll revert the VSCode extension to rule that out and let you know.

Cheers,

**Comment by code-asher** [comment]
Awesome!  I also found out that whether our proxy is used depends on the value for `http.proxySupport`; if this is set to `on` or `off` then it will use the support in the plugin, but any other value will use the VS Code built-in.

**Comment by rhysjtevans** [comment]
@code-asher I've managed to work out how to enable trace logs on vscode, I noticed in the logs there was this output. (I've substituted values)
Also additional note worthy context, I've got the coder cli working through the proxy and I can ssh to the coder workspaces.

```
ProxyResolver#resolveProxy settings http://192.168.0.254:3128/https://coder.localdomain/api/v2/users/me PROXY 192.168.0.254:3128
```

I presume there's a concatenation/instantiation problem with the proxy?

**Comment by code-asher** [comment]
Oh interesting!  That seems to come from https://github.com/microsoft/vscode-proxy-agent/blob/cbb23e7f00a653fad6a8d1b66389eb916ce62303/src/index.ts#L156 which is not our plugin, but maybe our plugin somehow causes the bug?  Does setting `http.proxySupport` to `off` or `on` make any difference?

**Comment by rhysjtevans** [comment]
oh good find! 
It is odd, I can see other calls to other sites that are outside of the coder extension and they appear how I'd envisage them to  appear to be i.e. not with the proxy URL as a prefix to the url

**Comment by code-asher** [comment]
Hmm that is odd, I wonder if our proxy stuff and VS Code's are somehow conflicting.

**Comment by code-asher** [comment]
But if that was the case, then I would expect pre-1.1.0 to have been working :thinking:

**Comment by rhysjtevans** [comment]
So interestingly, I had http_proxy and https_proxy set in the environment before opening vscode. I removed those vars, reopened VSCode and it worked! 

The proxy setting in VSCode were set to override.

**Comment by code-asher** [comment]
Ah interesting!  I think VS Code will prefer the env vars over the setting, so that makes some sense.  Glad it worked!

**Comment by rhysjtevans** [comment]
I suppose there's still a bug somewhere, but it will be difficult to allocate more time to troubleshooting for the time being. Thanks for the help and support @code-asher

**Comment by code-asher** [comment]
If you do poke into it further one day and find something, feel free to post any time and we can reopen the issue!
