### ISSUE TITLE
Failed to Open Workspace

### ISSUE THREAD

**Issue by Chukwueloka** [coder/vscode-coder#320]
Hello Guys;

I am trying to open my well running workspace on my desktop VS Code and geeting the below error:

Failed to open workspace
API GET to 'https://css14gblmhu7u.pit-1.try.coder.app/api/v2/buildinfo' failed.
Status code: None
Message: connect ETIMEDOUT 74.118.138.247:443
Detail: None

How do I fix this?
This is critical. 

Thanks in advance.
![Capture](https://github.com/user-attachments/assets/86ebf021-72d6-4712-a739-90290fe543ca)

**Comment by coadler** [comment]
That page seems to load correctly for me, it would seem you have problems connecting to our US based proxy server. The proxy server we host at `try.coder.app` is only meant for quickly standing up new deployments and is not intended for production use. I would recommend setting up HTTPS or a proxy yourself for critical use-cases.

**Comment by Chukwueloka** [comment]
Thank you so much. I will try as you just said.
