### ISSUE TITLE
Check workspace state again before starting

### ISSUE THREAD

**Issue by code-asher** [coder/vscode-coder#339]
We show a prompt to start the workspace if off, but if there is a delay here (like if the user left their computer overnight for example) and the workspace was since started by other means then they might accept the prompt and we could end up starting an already-started workspace.

This is another case where a unified start endpoint in the API would be useful, probably.

But for now what we can do is make one more query just before starting the workspace to make sure it is still stopped.

**Comment by stirby** [comment]
From @bpmct:

Steps to reproduce:
- Open VS Code Remote, connect to a workspace
- Pres 'Restart' on web ui for workspace
- Observe how VS Code desktop never reconnects when workspace starts back up. Again primary CTA is "Start"
- When "Start" is pressed, observe how the workspace is started again despite it already being started

Suggested improvements. Any one of these would be a better UX
- Auto reconnect when restart is complete
- Live poll and change CTA once started
- When "Start" is pressed, check if workspace is already started and simply connect instead
