### ISSUE TITLE
"Open Workspace" command pallette does nothing for me

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#341]
https://github.com/user-attachments/assets/dff0494b-25cd-4362-94b0-7cbcf439437b

The only logs I see in "Extension Host" are

```
2024-08-18 10:08:49.890 [info] ExtensionService#_doActivateExtension coder.coder-remote, startup: false, activationEvent: 'onCommand:coder.openFromSidebar'
```

**Comment by code-asher** [comment]
Oh interesting, it looks like the wrong command.  `coder.open` is the right one, `coder.openFromSidebar` should only be invoked from the sidebar.  We should hide this command from the palette, I think it never makes sense for a user to manually invoke it from the command palette.

**Comment by bpmct** [comment]
Can we prioritize this @stirby?

**Comment by code-asher** [comment]
Let me throw up a PR real swift, should just be a few lines
