### ISSUE TITLE
Workspace will double start if started from another location

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#342]
Steps to reproduce:
1. Open VS Code Remote, connect to a workspace
2. Pres 'Restart' on web ui for workspace
3. Observe how VS Code desktop never reconnects when workspace starts back up. Again primary CTA is "Start"
4. When "Start" is pressed, observe how the workspace is started again despite it already being started

Suggested improvements. Any one of these would be a better UX
- Auto reconnect when restart is complete
- Live poll and change CTA once started
- When "Start" is pressed, check if workspace is already started and simply connect instead

**Comment by bpmct** [comment]
https://www.loom.com/share/eaeda4387b8d4739bdbba5660f3a394f

**Comment by bpmct** [comment]
Oops this is very related to https://github.com/coder/vscode-coder/issues/339

**Comment by stirby** [comment]
@bpmct folding this into #339.
