### ISSUE TITLE
Coder hardly support self-signed certificates for Agent and vscode extension.

### ISSUE THREAD

**Issue by ArKam** [coder/vscode-coder#349]
Hi team,

I'm installing a coder instance on a personal lab (for demo at work) kubernetes, however, even if I can definitely see the potential of such tool, it can't be deployed correctly because as soon as you create a workspace, coder will complain about the workspace not being able to be reached as the agent can't be installed (logs shows an issue with the endpoint URL being a self-signed certificate).

The pretty same issue arise with vscode.

Couldn't we get an option that just ignore self-signed certificate? Something like a switch that would tell the user about the potential security issue he may face and then just do not try to verify self-signed certs?

Here is the issue that I faced with Coder 2.12.6 and vscode extension:
![image](https://github.com/user-attachments/assets/281abcf4-15f7-4b7c-858d-e41019bc91b1)

And here are my vscode informations:
![image](https://github.com/user-attachments/assets/ee0514af-6653-4bdc-a925-05cb971e0a27)

**Comment by code-asher** [comment]
I will go ahead and close this since we resolved the VS Code portion, and open another issue for doing something with the agent: https://github.com/coder/coder/issues/14500
