### ISSUE TITLE
Removes first matching Host block from ~/.ssh/config

### ISSUE THREAD

**Issue by aaronlehmann** [coder/vscode-coder#42]
If there is a `Host` block in ~/.ssh/config that matches the name used for the remote connection (for example `Host *`), this gets removed from the file when attempting to connect to a workspace.

I suspect this is caused by:

```ts
parsedConfig.remove({ Host: computedHost.Host })
```

`computedHost.Host` would evaluate to the `Host` value from the first block that matched (`*` in my example). It would be safer to pass an explicit value to remove.

**Comment by mafredri** [comment]
Linking issue #30 as it's kind of related.

**Comment by kylecarbs** [comment]
Ahh, certainly. Will fix ASAP.

**Comment by kylecarbs** [comment]
This should be fixed now! We have starting and ending comments. v0.1.6 has the fix.
