### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 

### ISSUE THREAD

**Issue by jackthenewbie** [coder/vscode-coder#49]
Got this one while trying to connect to my workspace, extension was installed normally, but when I try to connect it show me this error 
```
Error: ENOENT: no such file or directory, scandir 'c:\Users\name\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\bin'
```
when I navigate to coder.coder-remote, there isn't any ``bin`` dir

**Comment by mafredri** [comment]
Can confirm:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/147409/215752804-ac5a4fc2-a00e-48f6-9932-94a1a777b866.png">

As a workaround @jackthenewbie, you can create the `bin` folder manually and that will allow the extension to work.
