### ISSUE TITLE
Invalid session token! (Error: certificate has expired)

### ISSUE THREAD

**Issue by interpeix** [coder/vscode-coder#50]
Hi,

Got this error when trying to connect to my coder server. 
![image](https://user-images.githubusercontent.com/346059/215685632-309a91ee-483e-4c8e-8ab7-a3b40d32afe6.png)

I'm currently using Traefik ingress to publish coder and the certificate it's been issued by let's encrypt. Coder CLI can connect without issues using the same token, Any idea to find more info? or debug what certificate is expired?

**Comment by interpeix** [comment]
Tested again, with coder 0.22 and connects without issues. No changes from my side, only upgrade version, so....solved?

**Comment by cdrx** [comment]
I'm having the same issue. From one workstation, I get the `certificate has expired` error. From another workstation, it is working correctly.

I can't figure out why one system doesn't work.

For anyone who finds this and needs a quick workaround, boot VS Code with the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` set to 0.

```sh
export NODE_TLS_REJECT_UNAUTHORIZED=0
open /Applications/Visual\ Studio\ Code.app
```
