### ISSUE TITLE
Support different VSCode channels

### ISSUE THREAD

**Issue by phorcys420** [coder/vscode-coder#60]
https://user-images.githubusercontent.com/57866459/219793500-5c88b523-b0eb-448b-9d12-d2d8f0ea0d6a.mp4

<br/>

It's trying to open ``C:\Users\Phorcys\AppData\Roaming\Code\User\settings.json``
but my folder is actually ``C:\Users\Phorcys\AppData\Roaming\Code - Insiders\User\settings.json`` because my channel isn't stable.

I think there could be a VSCode API to get the config folder directly rather than having to test for channel and then use a relation table but I couldn't find it.

**Comment by kylecarbs** [comment]
Ahh, we should definitely fix this. I'm sure there's some maybe unofficial but janky way to grab it.

**Comment by matifali** [comment]
@phorcys420, could you investigate if there is an API to get this info and populate the issue with a suggested solution? Otherwise, I think we can close this for now, as most of our users do not use the insider version.

Feel free to reopen.
