### ISSUE TITLE
Older SSH client versions don't connect with VSCode/coder

### ISSUE THREAD

**Issue by groucho64738** [coder/vscode-coder#73]
Hi. I was testing out connecting to coder sessions through VSCode Desktop on Linux and just wanted to make an observation. On an Ubuntu 20.04 system, I was able to get my connection working. On a RedHat 7 system, SSH doesn't like the 'SetEnv' option.

On Ubuntu, the default ssh client is: OpenSSH_8.2p1
On RH7, it's OpenSSH_7.4p1

Any chance that this can be supported in older SSH clients? If not, maybe a warning in the readme about supported versions would be good.

**Comment by kylecarbs** [comment]
We have a fix coming up for this! cc @Emyrk

**Comment by groucho64738** [comment]
Thanks.

**Comment by kylecarbs** [comment]
You'll be able to override environment variable options inside of Coder now. cc @Emyrk

**Comment by plytro** [comment]
> You'll be able to override environment variable options inside of Coder now. cc @Emyrk

I'm confused by this statement. Is the intent to make [this line be configurable/optional](https://github.com/coder/vscode-coder/blob/main/src/remote.ts#L525 )?

When I installed the vscode extension and manually removed that bit from the local minified js file, the extension worked as expected. When that line is injected into the ~/.ssh/config file on RH7, the whole ssh config file is invalid and ssh to any machine stopped working for me.

**Comment by kylecarbs** [comment]
@plytro yup! These can be configured via the Coder deployment:

![image](https://user-images.githubusercontent.com/7122116/230536831-05d80460-12de-4984-adc9-146f8924d791.png)

If you override that var to empty, it _should_ be removed.

**Comment by kylecarbs** [comment]
Keep in mind connection tracking will break, so the number of active VS Code sessions detected by Coder won't be accurate, but that should be fine in some cases.

**Comment by plytro** [comment]
Can the docs be clarified? I initially read those docs as you must provide all the ssh config options. I had to read the code to see that it was merged with the defaults and then read a bit more to understand I need to pass in an empty string to remove a key.

**Comment by kylecarbs** [comment]
I was just thinking about this, and we should just not use `SetEnv` if the SSH client doesn't support it. I'll make this change!

**Comment by plytro** [comment]
Any idea when this change may become available or should we use the version that allows us to set this server side.

**Comment by kylecarbs** [comment]
I looked into parsing the version string a bit which we can do, but we'd need to look into the SSH experience cross-platform a bit more to ensure that's reliable. Could you do `ssh -V` for me and paste the output on your RHEL machine?

Feel free to use the var that sets server-side, that works too!

**Comment by Emyrk** [comment]
You can also add/remove ssh options on the extension itself: https://github.com/coder/vscode-coder/pull/74

**Comment by plytro** [comment]
The client side setting works for me as a user, however if we have dozens (I'd hope they're not all on such an old version of ssh) we'd ideally like everyone to just install the plugin and with minimal config on their end. The server side setting worked great for us.

```
$ ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by kylecarbs** [comment]
Fixed in the attached PR @plytro. New version coming out shortly.
