### ISSUE TITLE
pass headers to coder api 

### ISSUE THREAD

**Issue by Liorba** [coder/vscode-coder#76]
Hello coder team!
Our coder deployment is put behind a vpn so in order to send api calls to our control plan every request needs to have additional header holding  our vpn session token. 

in the vscode-coder code base, I noticed the user of axios, which can accept additional headers.
The problem resides in the fact that some of the api called are in the __coder__  codebase and I'm not sure what's the preferred way to propagate those headers to the axios client in the coder coder base.

please advice on the preferred path and I'll be happy contribute!

**Comment by Liorba** [comment]
@kylecarbs I've added support for VPN headers in #81

**Comment by code-asher** [comment]
Accidentally closed this, still need to merge in the plugin PR for this to be complete.
