### ISSUE TITLE
Failed to open workspace when using a custom user data dir

### ISSUE THREAD

**Issue by tiaden** [coder/vscode-coder#79]
When using a custom user data directory with vscode like in the example below, vscode-coder fails to open the workspace.(see below image) 
Example: code --user-data-dir=u:\test\user-data --extensions-dir=u:\test\ext-dir
Please note that creating a directory at  %appdata%\Code\User seems to solve the issue but I think the extension should use the custom user data directory instead in this case.
<img width="592" alt="Screenshot 2023-04-11 at 6 48 17 PM" src="https://user-images.githubusercontent.com/33968665/231262612-7871688f-d803-46fa-8476-62f308c30950.png">

**Comment by kylecarbs** [comment]
It definitely should! We'll fix this asap. cc @rodrimaia

**Comment by tiaden** [comment]
Thanks @kylecarbs !

**Comment by tiaden** [comment]
Any luck on getting a fix for this ?

**Comment by kylecarbs** [comment]
@tiaden fixed in the attached PR!

**Comment by tiaden** [comment]
@kylecarbs thank you very much !
