### ISSUE TITLE
Every new workspace must be trusted 

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/vscode-coder#83]
# Description

Everytime I start a new workspace a dialog gets displayed. This affects only opening new workspaces via **VS Code Desktop** button. This means opening a new local instance of VS Code via vscode: protocol-handler.

![image](https://user-images.githubusercontent.com/103434584/232571657-69c695a9-6d60-4933-a934-72294298299d.png)

# Expected behaviour

As we are opening a workspace from an safe environment there is no need to manually trust the workspace folder. Opening a new workspace takes me straight to the editor of VS Code.

**Comment by kylecarbs** [comment]
See https://github.com/microsoft/vscode-remote-release/issues/8381

**Comment by matifali** [comment]
Looks like an upstream issue. Closing. cc: @stirby
